apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rgb
  name: clientgo-app
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "update"]
- apiGroups: ["extensions", "apps"]
  #
  # at the HTTP level, the name of the resource for accessing Deployment
  # objects is "deployments"
  resources: ["deployments"]
  verbs: ["get", "list", "create", "update", "delete"]