apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows service account "default" to operate on pods
# and deployments in the "default" namespace.
# You need to already have a Role named "clientgo-app" in that namespace.
kind: RoleBinding
metadata:
  name: clientgo-app
  namespace: rgb
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: default # "name" is case sensitive
  namespace: default
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role # this must be Role or ClusterRole
  name: clientgo-app # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io