apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controllerruntime-app
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "update", "watch"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list", "create", "update", "delete", "watch"]