# permissions for end users to view rgbresourcemanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rgbresourcemanager-viewer-role
rules:
- apiGroups:
  - kd.kb.example.com
  resources:
  - rgbresourcemanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kd.kb.example.com
  resources:
  - rgbresourcemanagers/status
  verbs:
  - get
